### ISSUE TITLE
How do you connect to gameserver?

### ISSUE THREAD

**Issue by gabrielfgularte** [OpenSourceLAN/better-csgo-log-parser#1]
I have a local gameserver running. How can I connect to it?

**Comment by sirsquidness** [comment]
Do you mean, how to connect the better-srcds-log-parser application to receive logs from the game server?

I thought I had an example implementation in this repository, but apparently I don't.

Using [srcds-log-receiver](https://github.com/OpenSourceLAN/srcds-log-receiver), you can configure your srcds server with `log_address` to send logs in real time. The log receiver then parses the UDP messages and passes the payload of each message through the log parser.

```
var logReceiver = require("srcds-log-receiver"),
    SrcdsLogParser = require("better-srcds-log-parser").SrcdsLogParser;;
var options = {
    port: 9871  // this is the default
};
var parser = new SrcdsLogParser();

var receiver = new logReceiver.LogReceiver();
receiver.on("data", function(data) {
    if (data.isValid) {
       console.log(parser.parseLine(line));
    }
});
receiver.on("invalid", function(invalidMessage) {
    console.log("Got some completely unparseable gargbase: " + invalidMessage);
})

```

**Comment by gabrielfgularte** [comment]
> Do you mean, how to connect the better-srcds-log-parser application to receive logs from the game server?

Yes!

My server ports are `27005/udp` `27015` and `27020/udp`. The `9871` port is a better-srcds-log-parser default? What about my game server port connection?

You have declared a `options` var but you have never used it.

Thanks for your help! =D

**Comment by sirsquidness** [comment]
Yes, apologies - I copied and pasted a few snippets of code together. The `options` variable is not used, and the port it specifies is the default anyway.

The port of your game server does not matter. The readme on [the srcds-log-receiver](https://github.com/OpenSourceLAN/srcds-log-receiver) page has some more info. It works with a push system, not a pull. So the game server sends the logs to the app, the app does not connect to the game server. Port 9871 is what `srcds-log-receiver` listens on by default, and this is where we will configure srcds to send the logs.

If you run the program I pasted above on the same host as your srcds server, and then configure your game server with this:
```
mp_logdetail 3
logaddress_add 127.0.0.1:9871
log on
```
Then you should start seeing console output on the log receiver application.

**Comment by gabrielfgularte** [comment]
Amazing! Now I got it! Thank you very much!

**Comment by gabrielfgularte** [comment]
Also, I've created a Docker version, feel free to contribute: https://github.com/gabrielfgularte/docker-parse-csgo-gameserver

Thanks! :)
